config/routes.rb
Rails.application.routes.draw do

  root 'api/v1/recipes#index'
  
  namespace :api do
    namespace :v1 do
      post '/foods/search' => 'foods#search', as: :search_food
      resources :foods, only: [] do
        resources :weights, only: [:index]
      end
      resources :recipes, only: [:index, :create, :show] do
        resources :foods, only: [:index, :show]
        resources :nutrients, only: [:index, :show]
      end
    end
  end

  resources :users, only: [:create, :new]

  get 'users/login' => 'users#login_form'
  post 'users/login' => 'users#login'
  get 'users/logout' => 'users#logout'

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :food_group
  has_many :nutritions
  has_many :nutrients, :through => :nutritions
  has_many :weights

  include PgSearch
  pg_search_scope :search_by_desc, :against => [:short_desc, :long_desc], :using => {
                    :tsearch => {:prefix => true,
                                 :any_word => true
                                }
                  }

  def as_json(options={})
    super(:only => [:id, :long_desc])
  end
  
end

app/models/food_group.rb
class FoodGroup < ActiveRecord::Base
  has_many :foods
end

app/models/nutrient.rb
class Nutrient < ActiveRecord::Base
  has_many :nutritions
  has_many :foods, :through => :nutritions
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
  belongs_to :nutrient
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :recipe_nutrient_joins
  has_many :nutrients, through: :recipe_nutrient_joins
  has_many :recipe_food_joins
  has_many :foods, through: :recipe_food_joins

  accepts_nested_attributes_for :recipe_food_joins
end

app/models/recipe_food_join.rb
class RecipeFoodJoin < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :food
  belongs_to :weight
end

app/models/recipe_nutrient_join.rb
class RecipeNutrientJoin < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :nutrient
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :recipes

  validates :username, presence: true, uniqueness: true
  validates :email, :first_name, :last_name, presence: true
  validates :password, length: { minimum: 7 }
  validates :password_confirmation, presence: true
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :food

  def as_json(options={})
    super(:only => [:id, :description])
  end
end

app/controllers/api/v1/foods_controller.rb
class Api::V1::FoodsController < ApplicationController
  respond_to :html, :json

  def index
    response = []
    RecipeFoodJoin.where(recipe_id: params[:recipe_id]).each do |join|
      entry = {}
      entry[:name] = Food.find(join.food_id).long_desc
      entry[:amount] = join.amount
      entry[:weight] = Weight.find(join.weight_id).description
      response.push(entry)
    end
    # binding.pry
    render json: response
  end

  def show
    @food = Food.find_by(params[:id])
    render json: @food.as_json
  end
  
  def search
    @matches = Food.search_by_desc(params[:query]).limit(10);
    render json: @matches.as_json()
  end
end

app/controllers/api/v1/nutrients_controller.rb
class Api::V1::NutrientsController < ApplicationController
  respond_to :html, :json

  def index
    response = []
    RecipeNutrientJoin.where(recipe_id: params[:recipe_id]).each do |join|
      entry = {}
      nutrient = Nutrient.find(join.nutrient_id)
      entry[:name] = nutrient.name
      entry[:unit] = nutrient.unit
      entry[:amount] = join.amount
      response.push(entry)
    end
    # binding.pry
    render json: response
  end

  def show
  end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApplicationController
  
  respond_to :html, :json
  
  def index
    @current_user = User.find(1);
    @recipes = @current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    recipe = Recipe.new(recipe_params)
    recipe.user_id = @current_user.id
    recipe.save
    id = recipe.id
    params[:recipe_food_joins].each do |join|
      join[:recipe_id] = id
      RecipeFoodJoin.create(join.permit(:food_id, :weight_id, :amount, :recipe_id))
    end
    
    RecipeFoodJoin.where(recipe_id: id).each do |food|
      grams = Weight.find(food.weight_id).gram_weight /  Weight.find(food.weight_id).amount * food.amount
      Nutrition.where(food_id: food.food_id).each do |nutrition|
        currentAmount = nutrition.amount * grams / 100
        entry = RecipeNutrientJoin.find_or_create_by(recipe_id: id, nutrient_id: nutrition.nutrient_id);
        entry.update_attribute(:amount, entry.amount + currentAmount)
      end
    end
    render json: recipe.as_json(only: [:id, :name])
  end

  private

  def recipe_params
    params
      .permit(:name)
  end

  def food_joins_params
    params
      .permit(:recipe_food_joins)
  end
  
end

app/controllers/api/v1/weights_controller.rb
class Api::V1::WeightsController < ApplicationController
  def index
    @weights = Food.find(params[:food_id]).weights
    render json: @weights.as_json()                         
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authorize
    current_user = 1
  end

  private

  def require_login
    if !authorize
      flash[:error] = "User not authorized"
      redirect_to users_login_path
    end

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  
  def create
    @user = User.create(user_params)
    @user.save
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def login_form
  end
  
  def login
    user = User.find_by username: login_cred[:username]

    if user && user.authenticate(login_cred[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to new_sessions_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  
  private

  def user_params
    params
      .require(:user)
      .permit(:username, :email, :first_name, :first_name, :last_name, :password, :password_confirmation)
  end

  def login_cred
    params.permit(:username, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>FoodManager</title>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application'%>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
        <!--   <header> -->
        <!--     <div id="user-controls"> -->
        <!--          <% flash.each do |key, value| -%> -->
        <!--         <div class="flash <%= key %>"><%= value %></div> -->
        <!--          <% end -%> -->

        <!--          <% if @current_user -%> -->
        <!--              <%= @current_user.email %> -->
        <!--              <%= link_to "Sign out", users_logout_path %> -->
        <!--          <% else -%> -->
        <!--              <%= link_to "Sign in", users_login_path %> -->
        <!--              <%= link_to "Sign up", new_user_path %> -->
        <!--          <% end -%> -->
        <!--     </div> -->
        <!-- </header> -->
        
        <%= yield %>
        
        <%= yield :app %>
        <div id="container">
        </div>
        </div>
    </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= render 'inner_form', f: f %>
<% end %>

app/views/users/_inner_form.html.erb
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>

app/views/users/login_form.html.erb
<%= form_tag('/users/login') do %>
    <%= label_tag :username, 'Username' %>
    <%= text_field_tag  :username %>

    <%= label_tag :password, 'Password' %>
    <%= password_field_tag  :password %>

    <%= submit_tag 'Log In' %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>